### ISSUE TITLE
error building visual studio project

### ISSUE THREAD

**Issue by suhaskm** [Sitecore/Reference-Storefront#8]
Dear Team,

I have a TDS project and when I build the project I get below issue.

Adding item sitecore\templates..........\some.item to package
2>                      **Inner Exception Failed to load version 1 for language en(System.Exception):**
2>                         at Sitecore.Data.Serialization.ObjectModel.SyncVersion.ReadVersion(Tokenizer reader)
2>                         at Sitecore.Data.Serialization.ObjectModel.SyncItem.ReadItem(Tokenizer reader, Boolean assertVersion)
2>                      **Exception Error reading item: /sitecore/templates/........./__Standard Values(System.Exception):**
2>                         at Sitecore.Data.Serialization.ObjectModel.SyncItem.ReadItem(Tokenizer reader, Boolean assertVersion)
2>                         at Sitecore.Update.Data.Items.ContentDataItem.GetItem()
2>                         at Sitecore.Update.Data.Items.ContentDataItem.get_DatabaseName()
2>                         at HedgehogDevelopment.SitecoreProject.PackageBuilder.PackageBuilder.d(List`1 ?, d ?, String ?, IEnumerable`1 ?, HashSet`1 ?)
2>                         at HedgehogDevelopment.SitecoreProject.PackageBuilder.PackageBuilder.d(d ?)
2>                         at HedgehogDevelopment.SitecoreProject.PackageBuilder.y.d(String[] ?)

Note :The standard values as some HTML in rich text.Can this be a problem?

**Comment by mswift** [comment]
Did you ever resolve this?  I am experiencing the same issue.

**Comment by SorenKerrn** [comment]
We tested and released Sitecore Reference Storefront 10.3.158. Other versions are unchanged. Which version are you trying out?

**Comment by mswift** [comment]
Actually I wasn't getting it in while using Reference Storefront.  I was seeing it in a build server, but thought you might have insight into why HTML in a rich text field of a standard values item causes such an odd exception.
